id: P4C0642FA
initial_creation_type: input
source_metadata:
  title: Tulku Urgyen Rinpoche
  language: bo
  description: 'Texts by and about Tulku Urgyen Rinpoche (sprul sku o rgyan rin po
    che, 1920–1996), one of the most celebrated teachers of Dzogchen and Mahāmudrā
    in recent times:'
  volume:
    4b26b72533fb4c42bcb19772b0f74cf2:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Calling the Guru from Afar
    bf5c079d3a6b4e148b71e40c11130eb9:
      title: In Praise of the Hidden Valley of Kyimolung
      parent: Pilgrimage
created_at: '2022-03-01T01:58:23.919148'
last_modified_at: '2022-03-01T01:58:23.919150'
